### ISSUE TITLE
Ruby-Group-Capstone-Project

### ISSUE THREAD

**Issue by tsheporamantso** [Rifat8080/ruby-group-capstone#5]
This is Github project link: https://github.com/Rifat8080/ruby-group-capstone/projects/1
- [ ] There are 3 members in our group
     - [ ] Team member 1: @tsheporamantso - Assigned User Interface task 
     - [ ] Team member 2: @erickma1- Assigned Database task
     - [ ] Team member 3: @Rifat8080  - Assigned Logic Task

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @tsheporamantso, @erickma1 and @Rifat8080,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly provide the link to your Kanban board

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by danmainah** [comment]
Hi @tsheporamantso , @erickma1 and @Rifat8080 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Set up the Kanban board correctly with all required columns.
✔️ Ensured all cards have a title, description, number of points and assigned to a team member.

# Required Changes ♻️
- [x] @Team Great work adding tasks in the Kanban board, however we are supposed to ensure each task is in its card and the tasks are not combined in a single card, kindly move the tasks from the highlighted cards below to their card:
![image](https://github.com/Rifat8080/ruby-group-capstone/assets/61408860/2aa4983f-8d1e-4261-8fee-99cb997e7919)

![image](https://github.com/Rifat8080/ruby-group-capstone/assets/61408860/10857b17-efb3-4b5c-b224-1be2fc42f327)
![image](https://github.com/Rifat8080/ruby-group-capstone/assets/61408860/9d9a6e5d-3de8-4f99-9e0d-7e32e3366693)
![image](https://github.com/Rifat8080/ruby-group-capstone/assets/61408860/6a9e3fb9-6849-460f-89f4-3a0d49926394)
![image](https://github.com/Rifat8080/ruby-group-capstone/assets/61408860/5f3d94b2-c141-4cc5-8a4f-1cc9ef65bcac)
![image](https://github.com/Rifat8080/ruby-group-capstone/assets/61408860/b13c9723-fb14-4296-84d1-109795e57478)



- [x] @Team Kindly consider interchanging the description between this group tasks [[2pt] Implement methods - Task2 - [TM#3] #8](https://github.com/Rifat8080/ruby-group-capstone/issues/8) and [[2pt] Implement methods[Group Task] #3](https://github.com/Rifat8080/ruby-group-capstone/issues/3) so that each task has the correct description.


- [ ] @Team Great work adding requirements for group members, however, I discovered you didn't follow the instructions for each member to work on tasks allocated for that member eg Team member 1 should work for tasks of Team member 1 and group tasks only, in your case you have allocated tasks for Team member 3 and Team member 2, this is specified to ensure fair distribution of tasks and tests skills of members in all areas of the app development.
![image](https://github.com/Rifat8080/ruby-group-capstone/assets/61408860/27132439-7c7d-4633-bd59-579a1e1fd15c)

- [x] @Team Kindly ensure fair distribution of tasks Team member 1 is doing way more tasks than any other member which is unfair, kindly ensure fair distribution of tasks among members.

- [ ] @Team Kindly ensure all tasks are added after implementing the above changes.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by DammyShittu** [comment]
Hi @tsheporamantso, @erickma1 and @Rifat8080,

## Highlights
✔️ Assigned tasks

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly remove this task or put it to good use.

  ![image](https://github.com/Rifat8080/ruby-group-capstone/assets/54848363/e3397953-205c-404b-8956-1e0637ad1bcb)

- [ ] Kindly read the instructions from the previous reviewer carefully. You are confusing your tasks a lot. From this image, you can see that @erickma1 identifies as TM#1 and TM#2, and also has tasks from Team members 1, 2, and 3 from the guidelines. Kindly go through your tasks thoroughly and avoid misplacing tasks and their assignees. Choose who is Team Member 1, assign all Team Member 1 tasks to them, and update your task titles to avoid confusion; same with Team member 2 and 3.

  ![image](https://github.com/Rifat8080/ruby-group-capstone/assets/54848363/b7d7b777-d91e-4483-b1d7-16e35b7d29a9)

- [ ] The same issue occurs for @tsheporamantso. He has tasks designated for Team member 1, 2 and 3.

  ![image](https://github.com/Rifat8080/ruby-group-capstone/assets/54848363/7152b216-aa67-409c-bb68-945e61c26b7c)

  For example, team member 1 should be only be assigned to these tasks, along with the group tasks. He should not have any task belonging to team member 2 or 3.

  ![image](https://github.com/Rifat8080/ruby-group-capstone/assets/54848363/afd1dad1-da88-428f-9564-b16d98c2db7e)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brainconnect93** [comment]
## Status: Approved :heavy_check_mark:

Hi @tsheporamantso, @erickma1 & @Rifat8080, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Task properly assigned ✔️
- Kanban board created ✔️
- Descriptive issues summary✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
